// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLm5uul3SQ4ZkiyukN4mEF4Iy16v0Xjo',
    appId: '1:1065706073752:web:5eac4d38f901bc63856aed',
    messagingSenderId: '1065706073752',
    projectId: 'hairilhumsani-97f76',
    authDomain: 'hairilhumsani-97f76.firebaseapp.com',
    databaseURL: 'https://hairilhumsani-97f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hairilhumsani-97f76.appspot.com',
    measurementId: 'G-X27RBKF4TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmqDu3zXlYi7SXd1fKm7netDTT5xdB5mk',
    appId: '1:1065706073752:android:780ff10f510f6ac7856aed',
    messagingSenderId: '1065706073752',
    projectId: 'hairilhumsani-97f76',
    databaseURL: 'https://hairilhumsani-97f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hairilhumsani-97f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDugNO24GgrQ-8MJr3PVONofJ_GUStKdRo',
    appId: '1:1065706073752:ios:f16e995c80d4fc05856aed',
    messagingSenderId: '1065706073752',
    projectId: 'hairilhumsani-97f76',
    databaseURL: 'https://hairilhumsani-97f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hairilhumsani-97f76.appspot.com',
    iosClientId: '1065706073752-f1gg5amuooijhesnnp40ca4hbtfrft8a.apps.googleusercontent.com',
    iosBundleId: 'com.testing.helloworld2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDugNO24GgrQ-8MJr3PVONofJ_GUStKdRo',
    appId: '1:1065706073752:ios:6d64b61b9497479c856aed',
    messagingSenderId: '1065706073752',
    projectId: 'hairilhumsani-97f76',
    databaseURL: 'https://hairilhumsani-97f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hairilhumsani-97f76.appspot.com',
    iosClientId: '1065706073752-r60v8gsg77019hjiv7o5gmd5ikutsjud.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloworld',
  );
}
